title: Dylan Young
description: Data Science Portfolio
baseurl: ""  # leave empty for main site
url: "https://dylan-j-young.github.io"
theme: minima  # use GitHubâ€™s default Jekyll theme to start
markdown: kramdown

# Optional: links for header or footer
github_username: dylan-j-young
email: dylan.jing.young@gmail.com